# Generated by Django 2.0.2 on 2018-07-31 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile_approved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='service_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorsProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_link', models.URLField(blank=True)),
                ('phone_number', models.CharField(max_length=264)),
                ('logo', models.ImageField(blank=True, upload_to='logo')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('facebook_page', models.CharField(max_length=264)),
                ('twitter_page', models.CharField(max_length=264)),
                ('address_one', models.CharField(max_length=264)),
                ('address_two', models.CharField(max_length=264)),
                ('town_city', models.CharField(max_length=264)),
                ('country', models.CharField(max_length=264)),
                ('postal_address', models.CharField(max_length=264)),
                ('pin_number', models.CharField(max_length=264)),
                ('b_type', models.CharField(max_length=264)),
                ('payments_accepted', models.CharField(max_length=264)),
                ('insurance', models.CharField(max_length=3)),
                ('brief', models.CharField(max_length=264)),
                ('description', models.TextField(max_length=2000)),
                ('typical_clients', models.CharField(max_length=264)),
                ('location', models.CharField(default='', max_length=264)),
                ('service_area', models.CharField(max_length=264)),
                ('video_url', models.CharField(default='video url', max_length=264)),
                ('video_description', models.CharField(default='description', max_length=264)),
                ('profile_approved', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.profile_approved')),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.service_category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
