# Generated by Django 2.0.2 on 2018-07-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180731_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_approved',
            name='approved',
            field=models.CharField(default='No', max_length=100, unique=True),
        ),
    ]
