# Generated by Django 2.0.5 on 2018-10-06 16:01

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181005_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorsprofile',
            name='logo',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/logo'), upload_to='logo'),
        ),
        migrations.AlterField(
            model_name='vendorsprofile',
            name='profile_pic',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/profile_pic'), upload_to='profile_pics'),
        ),
    ]
