# Generated by Django 2.0.5 on 2018-10-06 16:42

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181006_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorsprofile',
            name='logo',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/logo'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='vendorsprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/profile_pic'), upload_to=''),
        ),
    ]
