# Generated by Django 2.0.5 on 2018-08-07 18:49

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180731_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorsprofile',
            name='logo',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/media/logo'), upload_to='logo'),
        ),
        migrations.AlterField(
            model_name='vendorsprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/media/profile_pic'), upload_to='profile_pics'),
        ),
    ]
