# Generated by Django 2.0.5 on 2018-10-06 17:40

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181006_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorsprofile',
            name='logo',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/media/logo'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='vendorsprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/media/profile_pic'), upload_to=''),
        ),
    ]
