# Generated by Django 2.0.5 on 2018-10-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181006_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorsprofile',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logo'),
        ),
        migrations.AlterField(
            model_name='vendorsprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
