# Generated by Django 2.0.5 on 2018-10-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20181008_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_approved',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
