# Generated by Django 2.0.5 on 2018-10-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20181008_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_approved',
            name='approved',
            field=models.CharField(default='False', max_length=5, unique=True),
        ),
    ]
