# Generated by Django 2.0.5 on 2018-10-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20181009_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_approved',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
