# Generated by Django 2.0.5 on 2018-10-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20181009_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorsprofile',
            name='profile_approved',
        ),
        migrations.AddField(
            model_name='vendorsprofile',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile_approved',
            name='approved',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
