# Generated by Django 2.0.5 on 2018-11-05 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='contact_mobile',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='group',
            name='event_date',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AlterField(
            model_name='group',
            name='service_category',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=264, unique=True),
        ),
    ]
