# Generated by Django 2.0.5 on 2018-11-07 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0003_auto_20181105_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='contact_mobile',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+254722999999' or '0722999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
